### ISSUE TITLE
One-get/Chocolatey versions vs scoop

### ISSUE THREAD

**Issue by e12e** [lukesampson/scoop-extras#103]
Hi,

am I correct in assuming that there's no automated import from Chocolatey/OneGet to scoop?

Would making something like that make sense?

For example, I've just found scoop, and added the "extra" bucket -- and installed OneGet (via scoop) -- and I find:

```powershell
~ $ scoop search vlc
extras bucket:
  vlc (2.2.0)
```

```powershell
~ $ Find-Package -Name vlc

Name                          Version      Status       ProviderName     Source           Summary
----                          -------      ------       ------------     ------           -------
vlc                           2.2.1        Available    Chocolatey       chocolatey       VLC Media Player
```

Now, I see that I could (should) fork this repo, and update https://github.com/lukesampson/scoop-extras/blob/master/vlc.json to point to http://get.videolan.org/vlc/2.2.1/ -- but seeing as the meta-data is already present(?) for OneGet would it make sense to wrap that from scoop?

Ideally, one would like upstream (like videolan in this case) to just have to publish one set of meta-data to one index in order for it to be picked up by package managers (as long as there's no need for custom build/installers).

Thank you for scoop btw -- first time in a looong time I've *enjoyed* playing a bit with the command line on windows.

**Comment by deevus** [comment]
I suppose it depends on whether we trust that OneGet (chocolately) installs software the way that Scoop likes. I'm pretty sure it just happily pollutes your path for just about every install, whereas with Scoop: adding extra things to the user's path has to be explicit.

**Comment by lukesampson** [comment]
Yes it's an interesting idea, but it does go slightly against the way Scoop was designed.

As @deevus said, I *think* One-Get/Chocolatey often just download and execute MSI installers, which can have a lot of side-effects (path pollution, registry entries, files placed in various places in file system), require admin UAC elevation, and don't always make things work immediately and nicely from the command line.

Scoop on the other hand is meant to prove that installing programs doesn't need to be so obscure. With Scoop you can usually see everything that's happening just by reading the manifest—usually just files are downloaded, extracted and linked into your command path. MSI installers are just treated as archives—the files are extracted and nothing is executed.

I realise this is a bit of an ideological stance, not just a pragmatic approach to installing things :)

But in a way, just wrapping the Chocolatey/One-Get package would not be enough information for Scoop, because even though Scoop does less work during installs, it's more explicit about what needs to be done, and I don't think that information is always present in Chocolatey.

Thanks for the idea though, and I'm glad to hear you're enjoying playing with the command line. Feel free to re-open this if we're missing something—I haven't looked at One-Get or Chocolatey for a while.
