### ISSUE TITLE
[Request] Add Fork

### ISSUE THREAD

**Issue by stannynuytkens** [lukesampson/scoop-extras#1094]
[Fork ](https://git-fork.com/windows) is a popular Git GUI for Mac but they recently released a Windows version.

I'm not sure on how to create the manifest file regarding the updates.

Some findings:

- Fork has an auto updating process of its own?
- The download link is ubiquitous: [https://git-fork.com/update/win/ForkInstaller.exe](https://git-fork.com/update/win/ForkInstaller.exe)
- The only way to check for a new version is to check the release notes page but this is a HTML page...
I could Regex out the version using `Fork\s([0-9]{1}\.[0-9]+)` but don't know if that's possible?

Fork installation seems pretty basic except for it needing git configuration (username, email)
and default code directory...

![image](https://user-images.githubusercontent.com/1488543/43659127-5436b2ea-975b-11e8-94d1-c6e70d438b66.png)

The installer seems to contain only the updater and the files packaged as a nuget package.

![image](https://user-images.githubusercontent.com/1488543/43659358-11f04706-975c-11e8-9338-de5f35c9178e.png)

Any help on getting me started?

**Comment by r15ch13** [comment]
I would recommend this:
```json
{
    "homepage": "https://git-fork.com/",
    "version": "1.19.0",
    "url": "https://git-fork.com/update/win/Fork-1.19.0-full.nupkg#/dl.7z",
    "hash": "sha1:f4a10adee420932bac2379ebe6931b3729a218dd",
    "extract_dir": "lib\\net45",
    "bin": "Fork.exe",
    "shortcuts": [
        [
            "Fork.exe",
            "Fork"
        ]
    ],
    "checkver": {
        "url": "https://git-fork.com/update/win/RELEASES",
        "re": "Fork-([\\d.]+)-full.nupkg",
        "reverse": true
    },
    "autoupdate": {
        "url": "https://git-fork.com/update/win/Fork-$version-full.nupkg#/dl.7z",
        "hash": {
            "url": "$baseurl/RELEASES"
        }
    }
}
```
Don't know what to add to the `license` property.

**Comment by r15ch13** [comment]
Urgh, it searches for Git in a hardcoded path ...
`C:\Users\<user>\AppData\Local\Fork\git\bin\git.exe`

**Comment by stannynuytkens** [comment]
@r15ch13 yeah, it comes with git-portable... ;,,;
Maybe we could remove that and set git as a dependency and link it?
Anyway, nice configuration to get me going!

**Comment by DanPristupov** [comment]
Hi guys. I'm the Fork developer and I just accidentally run into this issue.

Currently Fork has a bit complicated installation and update processes because of the Squirrel framework:

- Squirrel installer installs Fork to %localappdata% directory
- On first run Fork extracts the official 7z git archive into the same directory

I'm planning to improve this in the near future. Most probably I will switch to an MSI installer.

**Comment by Ash258** [comment]
Now everything is fine for this scoop installer, but Git is problem. Git path is hardcoded inside source (https://github.com/lukesampson/scoop-extras/issues/1094#issuecomment-410347584) and would be awesome if we could set where to look for git (some ini file, registry, switch, ...)

**Comment by DanPristupov** [comment]
It's always `%localappdata%\fork\git`, but I don't get why you need that. Fork will ask for user credentials and setup git on the first run anyway. Or do you want to avoid the welcome screen completely?

**Comment by Ash258** [comment]
Why to use your boundled git, when you have git already installed?

Scoop uses git for almost everything == Everyone who installed scoop have git. So no need to use that boundled.

**Comment by r15ch13** [comment]
@DanPristupov Like @Ash258, Scoop requires Git, so it's most definitely in the `%PATH%`. A simple check to use an existing Git installation would save some disk space. 😄
SourceTree, for example, can use a build Git or a systemwide version.
Scoop also sets `%GIT_INSTALL_ROOT%` (which is used by [Cmder](http://cmder.net/))  to point to the correct path.

The Squirrel installer is no problem for Scoop. We just download the `.nupkg` instead of the setup.exe.

If you're going to change the installation routine anyway, may I ask if you could provide a simple 7z or zip file and `SHA256` checksums? :smile:

**Comment by r15ch13** [comment]
@DanPristupov any news about the installer change? :smile:

**Comment by DanPristupov** [comment]
@r15ch13 no, I'm too busy, unfortunately. There are too many more important feature requests.

**Comment by r15ch13** [comment]
@DanPristupov A check if `%LocalAppData%\Fork\gitInstance\2.20.1\bin\git.exe` is available and fallback  to `git.exe` from `%PATH%` would solve this issue.

**Comment by Velgus** [comment]
I didn't even notice this issue when I made it, but I made a Fork manifest in my own bucket. It's a bit hack-y, but it works well enough for my purposes.
```
{
    "version": "1.37.2",
    "description": "A fast and friendly git client for Mac and Windows",
    "homepage": "https://git-fork.com/",
    "license": "https://git-fork.com/license",
    "url": "http://fork.dev/update/win/Fork-1.37.2-full.nupkg#/dl.7z",
    "hash": "sha1:abaa753d9cbeeeb157ec9ba7b5865bf7a2979986",
    "installer": {
        "script": [
            "$versionPattern = \"([\\d]+\\.)+[\\d]\"",
            "$gitZipPattern = [regex]::escape(\"PortableGit-\") + \"$versionPattern\" + [regex]::escape(\"-64-bit.7z\")",
            "$zips = Get-ChildItem \"$dir\\lib\\net45\" *.7z",
            "$gitZip = $zips -match $gitZipPattern | Foreach {$matches[0]}",
            "$gitVersion = $gitZip -match $versionPattern | Foreach {$matches[0]}",
            "Expand-7zipArchive \"$dir\\lib\\net45\\$gitZip\" \"$env:LOCALAPPDATA\\fork\\gitInstance\\$gitVersion\"",
            "\"$env:LOCALAPPDATA\\fork\\gitInstance\\post-install.bat\" | out-null",
            "Move-Item \"$dir\\lib\\net45\\*.*\" \"$dir\" -Force",
            "Remove-Item -LiteralPath \"$dir\\lib\", \"$dir\\_rels\", \"$dir\\package\", \"$dir\\[Content_Types].xml\", \"$dir\\fork.nuspec\", `",
            "\"$dir\\7z.exe\", \"$dir\\7z.dll\", \"$dir\\$gitZip\", \"$dir\\Fork_ExecutionStub.exe\" -Force -Recurse"
        ]
    },
    "uninstaller": {
        "script": [
            "if(Test-Path \"$env:LOCALAPPDATA\\fork\\gitInstance\") {",
            "    Remove-Item -LiteralPath \"$env:LOCALAPPDATA\\fork\\gitInstance\" -Force -Recurse",
            "}"
        ]
    },
    "bin": "Fork.exe",
    "shortcuts": [
        [
            "Fork.exe",
            "Fork"
        ]
    ],
    "checkver": {
        "url": "http://fork.dev/update/win/RELEASES",
        "regex": "Fork-([\\d.]+)-full.nupkg",
        "reverse": true
    },
    "autoupdate": {
        "url": "http://fork.dev/update/win/Fork-$version-full.nupkg#/dl.7z",
        "hash": {
            "url": "$baseurl/RELEASES"
        }
    }
}
```

**Comment by stannynuytkens** [comment]
> I didn't even notice this issue when I made it, but I made a Fork manifest in my own bucket. It's a bit hack-y, but it works well enough for my purposes.
> 
> ```
> {
>     "version": "1.37.2",
>     "description": "A fast and friendly git client for Mac and Windows",
>     "homepage": "https://git-fork.com/",
>     "license": "https://git-fork.com/license",
>     "url": "http://fork.dev/update/win/Fork-1.37.2-full.nupkg#/dl.7z",
>     "hash": "sha1:abaa753d9cbeeeb157ec9ba7b5865bf7a2979986",
>     "extract_dir": "lib\\net45",
>     "installer": {
>         "script": [
>             "$versionPattern = \"([\\d]+\\.)+[\\d]\"",
>             "$gitZipPattern = [regex]::escape(\"PortableGit-\") + \"$versionPattern\" + [regex]::escape(\"-64-bit.7z\")",
>             "$zips = Get-ChildItem \"$dir\" *.7z",
>             "$gitZip = $zips -match $gitZipPattern | Foreach {$matches[0]}",
>             "$gitVersion = $gitZip -match $versionPattern | Foreach {$matches[0]}",
>             "Expand-7zipArchive \"$dir\\$gitZip\" \"$env:LOCALAPPDATA\\fork\\gitInstance\\$gitVersion\"",
>             "cmd.exe /c \"$env:LOCALAPPDATA\\fork\\gitInstance\\$gitVersion\\post-install.bat\"",
>             "Remove-Item -LiteralPath \"$dir\\lib\", \"$dir\\[Content_Types].xml\", \"$dir\\7z.exe\", `",
>             "\"$dir\\7z.dll\", \"$dir\\$gitZip\", \"$dir\\Fork_ExecutionStub.exe\" -Force"
>         ]
>     },
>     "uninstaller": {
>         "script": [
>             "if(Test-Path \"$env:LOCALAPPDATA\\fork\\gitInstance\") {",
>             "    Remove-Item -LiteralPath \"$env:LOCALAPPDATA\\fork\\gitInstance\" -Force -Recurse",
>             "}"
>         ]
>     },
>     "bin": "Fork.exe",
>     "shortcuts": [
>         [
>             "Fork.exe",
>             "Fork"
>         ]
>     ],
>     "checkver": {
>         "url": "http://fork.dev/update/win/RELEASES",
>         "regex": "Fork-([\\d.]+)-full.nupkg",
>         "reverse": true
>     },
>     "autoupdate": {
>         "url": "http://fork.dev/update/win/Fork-$version-full.nupkg#/dl.7z",
>         "hash": {
>             "url": "$baseurl/RELEASES"
>         }
>     }
> }
> ```
> 
> I handled the git extraction through the script so I could remove unnecessary files as part of the install. Removing the 7z stuff also prevents the Fork setup screen from throwing any errors.

Awesome, I'll test this on my machine!

**Comment by linsui** [comment]
This is my try based on @r15ch13 's manifest, thanks! I just worry if it will break down when git is updated. If there is no problem i'll pr.

```
{
    "version": "1.37.2",
    "homepage": "https://git-fork.com/",
    "description": "A fast and friendly git client for Mac and Windows",
    "license": {
        "identifier": "Freeware",
        "url": "https://git-fork.com/license"
    },
    "url": "https://git-fork.com/update/win/Fork-1.37.2-full.nupkg",
    "hash": "sha1:abaa753d9cbeeeb157ec9ba7b5865bf7a2979986",
    "extract_dir": "lib\\net45",
    "bin": "Fork.exe",
    "post_install": [
        "$version = (Get-Item \"$dir\\PortableGit*\") -Replace '[^\\d]+([\\d.]+).+', '$1'",
        "Remove-Item \"$dir\\PortableGit-*\", \"$dir\\7z*\" -Force -ErrorAction SilentlyContinue",
        "if(!(Test-Path \"$Env:LocalAppdata\\Fork\\gitInstance\")) {",
        "    New-Item \"$Env:LocalAppdata\\Fork\\gitInstance\\$version\" -ItemType Junction -Target \"$(appdir git $global)\\current\" -Force | Out-Null",
        "}"
    ],
    "shortcuts": [
        [
            "Fork.exe",
            "Fork"
        ]
    ],
    "checkver": {
        "url": "https://git-fork.com/update/win/RELEASES",
        "regex": "Fork-([\\d.]+)-full.nupkg",
        "reverse": true
    },
    "autoupdate": {
        "url": "https://git-fork.com/update/win/Fork-$version-full.nupkg",
        "hash": {
            "url": "$baseurl/RELEASES"
        }
    }
}
```

**Comment by Velgus** [comment]
Currently that manifest will not work if the user doesn't have scoop's `git` installed, or if they are instead using `git-with-openssh`.

**Comment by linsui** [comment]
> Scoop also sets %GIT_INSTALL_ROOT% (which is used by Cmder) to point to the correct path.

I just find that we can find git easily. How do you think about this idea? I have updated my manifest.

**Comment by Velgus** [comment]
I don't think that variable is an actual thing - at least not in scoop. I can't actually find any reference to it in relation to scoop aside from this thread, and one mention in a [Cmder project issue](https://github.com/cmderdev/cmder/issues/1479#issuecomment-335037827). 

It doesn't exist in my environment variables, and scoop doesn't seem to set it during installs or some such, so that just returns a blank string.

Also for note `(Get-Item \"$dir\\PortableGit*\") -Replace '[^\\d]+([\\d.]+).+', '$1'"` appears to return the Fork version number, but the folder Fork looks for is AppData\Fork\gitInstance\<PortableGit Version Number>.

**Comment by linsui** [comment]
Thanks for your test. I found that it's set when scoop install git. Another way is `$(scoop which git)\..\..`. It works for me, too.
`(Get-Item \"$dir\\PortableGit*\") -Replace '[^\\d]+([\\d.]+).+', '$1'"` returns the git version in fork.

**Comment by Velgus** [comment]
That one appears to work with `git-with-openssh`, edited my above code.

I know it 'seems' like it should return the git version, but it doesn't. For testing purposes I changed the line in my manifest with `$gitVersion` to it, and it creates the folder as the Fork version.
![image](https://user-images.githubusercontent.com/4391565/62002150-3d901c80-b0b3-11e9-8892-28fa35765864.png)

**Comment by linsui** [comment]
It does work for me. I have test your manifest , if only change one line it does not work. Strange :confused: Could you test my manifest?

**Comment by Velgus** [comment]
Ah yeah, I figured out why - it has to do with it having been in the `installer` instead of `post_install`. No idea why it returns a value of the app version in that case though.

That aside, I feel the manifest is about as good as it can get now without modifications from the Fork developer's side. The only real things I prefer are:
- Removing a couple extra unnecessary files (the empty "lib" directory, and the execution stub which is only needed for the regular Squirrel install)
- Provide Fork's own git version as a back-up in case the user doesn't have git installed through scoop
- Remove the git installation/junction on uninstall, to prevent broken junctions or unnecessary git installations remaining between updates (in case the PortableGit version changes)

I've edited my manifest one more time to reflect my preferred version.

**Comment by linsui** [comment]
Great, could you pr? And please change the url. Now we don't need #/dl.7z for nupkg file and please use https url. I don't think we need to use the fork's git as scoop need git to work so there must be a git in the system.
It will not work in installer because when install there is not a current dir so the regex will match the fork version. It can be fixed with a more strict regex.

**Comment by Velgus** [comment]
Sure - will make those adjustments and PR shortly.
