### ISSUE TITLE
Request: DS4Windows

### ISSUE THREAD

**Issue by Guard13007** [lukesampson/scoop-extras#1290]
A utility for mapping PS4 controllers and a bunch of settings and whatnot: https://github.com/Jays2Kings/DS4Windows/releases

**Comment by Nefariis** [comment]
https://github.com/lukesampson/scoop-extras/pull/1298

**Comment by r15ch13** [comment]
Wouldn't it be better to use the more actively developed fork? https://github.com/Ryochan7/DS4Windows

**Comment by Nefariis** [comment]
@r15ch13 - Probably, I just know that this was the version of the application that he requested.

Is there a flag or a switch that you can set to download one, the other, or both?

**Comment by r15ch13** [comment]
No there is no flag/switch to do that.

**Comment by Nefariis** [comment]
Again, new here and I'm still figuring out best practices - 

If the original project is `Jays2Kings` and the request is `Jays2Kings` but the most recent update is currently `RyoChan7`'s fork - who would be the best project to pull from? 

Would if be better in this instance to create a manifest for each project and let the user decide when installing?

My only thoughts are backward compatibility issues - maybe he chose the original because it's the only one to work with his controller? Not trying to be difficult, just trying to learn.

**Comment by Guard13007** [comment]
Didn't know there was a more actively developed version, just went with what was pointed to by Googling. I would argue for the more actively development version because it's more recent (and I would *hope* better).

**Comment by DiabolusExMachina** [comment]
You should definitely use RyoChan7's fork. There is no reason for anyone to use the outdated unmaintained Version of Jays2Kings anymore.
