### ISSUE TITLE
Keep repo tidier by moving program json files to a separate directory

### ISSUE THREAD

**Issue by nitrocode** [lukesampson/scoop-extras#1320]
Great app! I've been considering moving from choco to scoop because of this extras bucket. Anyway, I was perusing the scoop extras directory today and was curious why all the json files were on the first level. 

If scoop extras ever gets as many packages as [homebrew cask](https://github.com/Homebrew/homebrew-cask/tree/master/Casks), the highest number of packages that will be visible by the browser is 1000.

>  Sorry, we had to truncate this directory to 1,000 files. 3,040 entries were omitted from the list. 

Also if a new user wants to learn more about this repo, they have to scroll down all the way to the bottom which is a bit of a hassle. This may also feel like the README for this repo will get less attention. I hypothesize that's why the readme is much smaller than scoop.

Would you consider creating an `apps` (or `makers` if scoops are related to icecream like in homebrew casks are related to beers) directory to clean up the root level?

**Comment by nitrocode** [comment]
@r15ch13 thoughts on this?

**Comment by r15ch13** [comment]
@Ash258 your recent changes with https://github.com/lukesampson/scoop/pull/2878 make this possible, I guess? Should we move the files? (Changes for the tests are probably not required because of https://github.com/lukesampson/scoop/blob/c3195915abc4ae23e72b08ba58fed2d2b079d6dd/test/Import-Bucket-Tests.ps1#L22-L25)

**Comment by Ash258** [comment]
I already use it in my buckets (https://github.com/Ash258/scoop-Ash258, https://github.com/Ash258/scoop-JetBrains) and it's working without any problem.

You only need to move scripts folder aswell. Follow instructions in PR description or my https://github.com/Ash258/GenericBucket repository for changed binaries.

**Comment by r15ch13** [comment]
Done
7d94c5692e6c6f9d9011730d4590703e626312fc
ff7c24db0945c3e315b74c648d2d4ad51b2820b5
bdd6c32cbf01baa84f418bfd9968c96fa0b4a218
a84b257fd9636d02295b48c3fd32826487ca9bd3

**Comment by Ash258** [comment]
@r15ch13 Youu forgot to move scripts folder. 

Tortoise SVN uses `buckdetdir` in script and now it will point to `bucket\scripts`.

https://github.com/lukesampson/scoop-extras/blob/a84b257fd9636d02295b48c3fd32826487ca9bd3/bucket/tortoisesvn.json#L58-L64

**Comment by r15ch13** [comment]
@Ash258 fixed with https://github.com/lukesampson/scoop-extras/commit/fe2bc999a1e1c4a803cc9f84ee33c5d642b45058

**Comment by rasa** [comment]
Since files in `/scripts` related to/are run from the .json files in `/bucket`, perhaps the directory should live under `/bucket` at `/bucket/scripts/` with each app having its own subdirectory: `/bucket/scripts/appname`?

Alternatively, we could dispense with `/scripts` and put each app's script in a `/bucket/appname` subdirectory. I prefer `/bucket/appname` as `/scripts` really serves no purpose, but either are fine (or just leaving it as is).
