### ISSUE TITLE
Package p4merge broken on install

### ISSUE THREAD

**Issue by bgshacklett** [lukesampson/scoop-extras#1762]
After installing, p4merge exits, without doing anything, immediately after being called. When called from the GUI, an error is received:

    ---------------------------
    p4merge.exe - System Error
    ---------------------------
    The code execution cannot proceed because MSVCR120.dll was not found. Reinstalling the program may fix this problem. 
    ---------------------------
    OK   
    ---------------------------

It looks like a dependency on the Visual C++ Runtime may not be met?

**Comment by rasa** [comment]
`scoop install extras/vcredist2013` is required. This could be added as a `depends` or ` suggest`

**Comment by bgshacklett** [comment]
Is there a defined criteria, in the Scoop project, for when something is listed as a dependency vs added to `suggest`? In this case, `p4merge` crashes on launch, so it seems like that would be a reasonable hard dependency.

**Comment by r15ch13** [comment]
Vcredist should only be suggested because it may already be installed on the users system.
scoop doesn't handle vcredist like other programs. E.g. it doesn't uninstall vcredist, it just removes the installer.

_Sent from my OnePlus5T using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by bgshacklett** [comment]
Got it; I'll update the PR accordingly.
