### ISSUE TITLE
MuseScore 3.0.4.5763 released

### ISSUE THREAD

**Issue by riaanvn** [lukesampson/scoop-extras#1788]
https://github.com/musescore/MuseScore/releases/download/v3.0.4/MuseScore-3.0.4-x86_64.msi
SHA256 Checksum: 3b12fb19fcd2b9bee3febc21df645434f20a0d656c7c9399c6013ccd1b6618e4

**Comment by riaanvn** [comment]
PR #1789 created to fix URL.

**Comment by shoogle** [comment]
The app manifests (JSON files) are updated automatically when a new version of an app is released (see [App Manifest Autoupdate](https://github.com/lukesampson/scoop/wiki/App-Manifest-Autoupdate)), so the problem is not with the URL but with the template it is generated from, which is stored in the `autoupdate` field of the JSON file. See [my comment](https://github.com/lukesampson/scoop-extras/pull/1789#discussion_r261839944) on your PR.
