### ISSUE TITLE
JDownloader 2 Clean Installers (No Adware!)

### ISSUE THREAD

**Issue by K-mikaZ** [lukesampson/scoop-extras#1815]
Here are the full, [adware-free JDownloader offline installer](http://jdownloader.org/jdownloader2)

from https://board.jdownloader.org/showpost.php?p=266023&postcount=246
`http://installer.jdownloader.org/ic/JD2SilentSetup_x86.exe`
`http://installer.jdownloader.org/ic/JD2SilentSetup_x64.exe`

**Comment by Gargauth** [comment]
Scoop doesnt use installer but directly uses only .jar file and expects user to install JRE manually instead of relying on Jdownloader installers. Jdownloader only installs adware/offers at install time, the resulting .jar file is the same whether it's from adware or no-adware installers or standalone jar file installer.

**Comment by Ash258** [comment]
Also there is still no version to find, so single nighly jar is much better solution.

**Comment by K-mikaZ** [comment]
> Scoop doesnt use installer but directly uses only .jar file and expects user to install JRE manually instead of relying on Jdownloader installers. Jdownloader only installs adware/offers at install time, the resulting .jar file is the same whether it's from adware or no-adware installers or standalone jar file.

ok, thank for the explanation

**Comment by thunderpants** [comment]
Never noticed any adware in Jdownloader though i do switch a few things in the settings.
