### ISSUE TITLE
obs-studio 23.2.0 not found

### ISSUE THREAD

**Issue by tomihawk** [lukesampson/scoop-extras#2271]
The URL for the recent update to version 23.2.0 of obs-studio is invalid.  I can see the 23.2 release on GitHub but the binary isn't offered through a download link on the main OBS Project website so maybe it was pulled, or the binary hasn't been uploaded yet.

**Comment by MCOfficer** [comment]
it seems that OBS's build pipeline is broken, in some way - the release didn't get published to github or their own website. It does, however, exist on their CDN:
https://cdn-fastly.obsproject.com/downloads/OBS-Studio-23.2-Full-x64.zip

Perhaps it would be feasible to use that URL instead of relying on github releases.

**Comment by MCOfficer** [comment]
it's back to normal with the update to 23.2.1 (dc93d807)

**Comment by tomihawk** [comment]
I guess since we've moved past the broken version there's no point in leaving the ticket open.
