### ISSUE TITLE
firefox@67.0.3: download via aria2 failed

### ISSUE THREAD

**Issue by zvikara** [lukesampson/scoop-extras#2319]

**Comment by issaclin32** [comment]
I tried it on my PC, but nothing went wrong.

Have you tried to install it again after waiting for a while? I think it's just caused by some connection issue with the official repository of Firefox(download.mozilla.org).

![download_test](https://user-images.githubusercontent.com/27724471/59900826-e6e85080-942b-11e9-9c07-dadd015ddb9f.png)

**Comment by rasa** [comment]
Closing as this issue is stale. Please reopen if this is still an issue.
