### ISSUE TITLE
anaconda3@2019.07 update error

### ISSUE THREAD

**Issue by edisoncks** [lukesampson/scoop-extras#2572]
Upgrading anaconda3 from 2019.03 to 2019.07 removes 2019.03 without prompting and does not preserve existing environments.

```
Checking hash of Anaconda3-2019.07-Windows-x86_64.exe ... ok.
Uninstalling 'anaconda3' (2019.03)
Running uninstaller... done.
Removing shim for 'python'.
Removing shim for 'pythonw'.
Removing shim for 'python3'.
Unlinking ~\scoop\apps\anaconda3\current
Installing 'anaconda3' (2019.07) [64bit]
Loading Anaconda3-2019.07-Windows-x86_64.exe from cache.
Running pre-install script...
Installing Anaconda 3. This can take up to 30 minutes on an HDD.
Running installer... done.
Linking ~\scoop\apps\anaconda3\current => ~\scoop\apps\anaconda3\2019.07
The system cannot find the path specified.
Creating shim for 'python'.
Creating shim for 'pythonw'.
Creating shim for 'python3'.
Persisting envs
'anaconda3' (2019.07) was installed successfully!
```

**Comment by rasa** [comment]
It persists the [envs](https://github.com/lukesampson/scoop-extras/blob/16994326a31d071262c28c61ad518db622f3b330/bucket/anaconda3.json#L32) directory. Are there other directories that need to be persisted?

**Comment by edisoncks** [comment]
I have installed anaconda since before the persist feature exists. What I
did when upgrading previously was to copy/move env directory from old
version to new version manually. However when upgrading to 2019.07, scoop
just deleted the old version without prompting, hence my env directory is
not preserved.

**Comment by rasa** [comment]
Yuk. Sorry you lost data. If you have a backup, you can copy it into the new envs directory, and you should be OK on future upgrades.

**Comment by edisoncks** [comment]
It's ok. By the way, is it the intended behavior to delete older version
when updating to newer version? This doesn't seem to happen when I update
other applications.

**Comment by niheaven** [comment]
No, it's not usual way to delete previous version. This only be done after you run `scoop cleanup`. Updating only redirects `current` link.

**Comment by rasa** [comment]
@edisoncks Can you check if the directory `C:\users\you\scoop\apps\anaconda3\2019.03\envs` exists?

**Comment by edisoncks** [comment]
@rasa Nope, the entire 2019.03 directory is gone.

**Comment by rasa** [comment]
That’s because the uninstall function using their installer [here](https://github.com/lukesampson/scoop-extras/blob/3dfe3ea0bd8964fad80b8cc0da2307e23f364995/bucket/anaconda3.json#L28).

What’s weird is the 2019.07 [update](https://github.com/lukesampson/scoop-extras/commit/50650cad4e7158e3b0e4d6c070346129dd5e5b48#diff-860e78ecc874c5cb001fbc4f9636a99b) didn’t change anything that should cause your issue.

The persist and uninstaller were added [here](https://github.com/lukesampson/scoop-extras/commit/95774fe9075254671f8602875bbfddab3d9f099a) in 2018.12.

@edisoncks Can you check if the directory `C:\users\you\scoop\persist\anaconda3\envs` exists?

**Comment by edisoncks** [comment]
@rasa The `~\scoop\persist\anaconda3\env` directory exists. The envs that I have recreated are located in this directory.
