### ISSUE TITLE
firefox-developer creates two apps

### ISSUE THREAD

**Issue by zfogg** [lukesampson/scoop-extras#2616]
windows thinks that there are two firefoxes, for some reason. setting the default web browser is a guessing game. perhaps it's because of the firefox shortcut?

**Comment by issaclin32** [comment]
I think this has nothing to do with **Scoop**. This problem is probably related to how **Firefox** registers its information on Windows.

For `Firefox`, Scoop will only extract files from the installer (not actually running the installer.), and create shortcuts according to the `bin` and `shortcut` section of the manifest.

From the **bin** and **shortcut** section of [firefox-developer.json](https://github.com/lukesampson/scoop-extras/blob/master/bucket/firefox-developer.json), you can see that the shortcuts are named as **firefox-dev, firefox-developer** (for terminal) and **Firefox Developer Edition** (for start menu shortcuts).

**Comment by zfogg** [comment]
@issaclin32 i only have firefox-developer installed. just tried on a new windows10 install. what i mean is that Windows 10 thinks there are two Firefox Developer apps, so I see two indistinguishable options when i try to set my default browser in Windows settings (for example).

**Comment by issaclin32** [comment]
OK. I see what you are saying.

I reproduced the problem by:
1. Run `scoop install firefox-developer`
1. Open **Firefox Developer Edition**, pin the program to the taskbar, and close Firefox.
1. Open Firefox by clicking the pinned icon.

The problem is caused by that Windows treats `(SCOOP_DIR)\apps\firefox-developer\nightly-20190811\firefox.exe` and `(SCOOP_DIR)\apps\firefox-developer\current\firefox.exe` as different programs.

I cannot think of any clever and safe way to fix the manifest. (other than creating shims and shortcuts manually in `installer.script`, which is prone to error and will not be accepted by the maintainers of **Scoop**), but you can simply avoid the problem by **deleting the `bin` and `shortcut` section** of [the manifest](https://github.com/lukesampson/scoop-extras/blob/master/bucket/firefox-developer.json), and **create the shortcuts by yourself**.

I think this problem happens in regular version of **Firefox** too (haven't test it yet though.)


![ff03](https://user-images.githubusercontent.com/27724471/62834055-c09ba000-bc79-11e9-974f-35a03ddd5faf.png)


![ff01](https://user-images.githubusercontent.com/27724471/62834058-c3969080-bc79-11e9-8d07-64b6a04c657f.png)


![ff02](https://user-images.githubusercontent.com/27724471/62834063-cabd9e80-bc79-11e9-816a-516a0ce293d0.png)

**Comment by zfogg** [comment]
@issaclin32 okay, understood. thanks for taking the time to reproduce! i may just install this app manually, without scoop, to solve. i'll close the issue but hopefully others will find via google :p

**Comment by ncwhale** [comment]
I have the same problem with firefox-portable installed from scoop, that's may not be a scoop problem but windows problem.
