### ISSUE TITLE
paint.net@4.2: hash check failed

### ISSUE THREAD

**Issue by maks232** [lukesampson/scoop-extras#2618]
paint.net.4.2.install.zip (8,7 MB) [===============================================================================================================================] 100%
Checking hash of paint.net.4.2.install.zip ... ERROR Hash check failed!
App:         extras/paint.net
URL:         https://www.dotpdn.com/files/paint.net.4.2.install.zip
First bytes: 50 4B 03 04 14 00 00 00
Expected:    097e8738d74b4c29694aea0f8bf7867769082aef0ca9e138880632cfd9de3335
Actual:      034274acf0413e6cfe3b1833ee7a88aae6e67a498658f30e62158b4afcb0d4af

**Comment by issaclin32** [comment]
It works fine on my PC. Probably just a connection issue.

**Comment by maks232** [comment]
Thanks for the reply. I'll try from another network when available and report.

**Comment by maks232** [comment]
I tried in several WiFi hotspots without success. Mobile network didn't work either. Network settings are set to Windows defaults as far as I know.
Please let me know if there is a way I can help.

**Comment by issaclin32** [comment]
Thanks for the report.

I tried to download again, but it still works fine here.
![paint](https://user-images.githubusercontent.com/27724471/63206515-5dca5e80-c0e8-11e9-9098-0f921947fbf1.png)

I can only guess it's probably country/region related issue. Maybe the website redirects user to different mirror sites based on country/region, and that mirror site contains a corrupted `paint.net.4.2.install.zip`

You can try run `scoop install paint.net --no-cache`
(just to make sure the problem is not caused by corrupted cache)

If above fails, please tell me which country/region are you in, so that I can try to re-produce the problem using a VPN.

**Comment by maks232** [comment]
I tried with no-cache option, still no success. 
I tried downloading from Austria and from Germany.

**Comment by rasa** [comment]
The hash in the manifest (034274acf0413e6cfe3b1833ee7a88aae6e67a498658f30e62158b4afcb0d4af) is correct. Please try again.

**Comment by issaclin32** [comment]
I just noticed that your manifest was not updated correctly. The hash value in the [latest version of the manifest](https://github.com/lukesampson/scoop-extras/blob/master/bucket/paint.net.json) is correct, but your manifest stays at the old version.

Resetting the extras bucket by running `scoop buckets rm extras && scoop bucket add extras` will solve the problem.

**Comment by maks232** [comment]
> I just noticed that your manifest was not updated correctly. The hash value in the [latest version of the manifest](https://github.com/lukesampson/scoop-extras/blob/master/bucket/paint.net.json) is correct, but your manifest stays at the old version.
> 
> Resetting the extras bucket by running `scoop bucket rm extras && scoop bucket add extras` will solve the problem.

this worked for me, thanks!
