### ISSUE TITLE
OpenVPN installation as a standard user

### ISSUE THREAD

**Issue by scott-8** [lukesampson/scoop-extras#3269]
I am unable to both update and uninstall my OpenVPN installation through scoop after the update, because the actions require the user to be an administrator. On my PC, I use a non-admin account, and when I need to install something, I just enter the Admin credentials in the UAC popup.

Is it possible to trigger UAC for the installation of OpenVPN instead of having a hard requirement that the user be an admin?

**Comment by Ash258** [comment]
Just spawn powershell as administrator and enter credentials there.

**Comment by scott-8** [comment]
I tried sudo before, and you need to be an admin to use it.

The elevated command prompt is a bit weird. After I open one, it doesn't recognize scoop as a command. Additionally, running `whoami` returns the administrator account. So in my case, doing this wouldn't work because installing something in the elevated command prompt would install it in the administrator's account, not mine.

**Comment by LoZeno** [comment]
@scott-8 you basically have the same setup I have (run as a standard user account which is different from the administrator account). The reason why the elevated command prompt does not recognise the scoop command is simply because the scoop folder is in your standard user's Path, not in the System PATH nor in the administrator user's path (and in your setup you are effectively switching user when you use the elevated command prompt)

I'll tell you how I went around it:
in my powershell profile, I added this:

```
function su {
    Start-Process powershell.exe -Verb RunAs -Args "-executionpolicy bypass -command Set-Location \`"$PWD\`"; $env:Path += ";$env:USERPROFILE\scoop\shims"; $args;" 
}
```

with that in your profile, you can run
`su scoop install OpenVPN`
You'll get the UAC prompt asking for your administrator account, will open a new elevate powershell window, will (temporarily) add your scoop installation to the path of your administrator account, and execute the command, then close the window.

If you're using Powershell Core, replace `powershell.exe` with `pwsh.exe`
If you don't want the administrator window to close when the command is concluded, add `-noexit` to the list of arguments.

**Comment by scott-8** [comment]
Thanks for this! I messed around with what you wrote, and I ended up with this:

```powershell
function su {
	Start-Process powershell.exe -Verb RunAs -Args "-executionpolicy bypass -noexit -command Set-Location \`"$PWD\`"; `$env:Path += \`";$env:USERPROFILE\scoop\shims\`"; `$env:SCOOP = \`"$env:USERPROFILE\scoop\`"; `$env:XDG_CONFIG_HOME = \`"$env:USERPROFILE\.config\`"; `$env:SCOOP_STARTMENU = \`"$([Environment]::GetFolderPath('startmenu'))\`"; $args; robocopy `$([System.IO.Path]::Combine([Environment]::GetFolderPath('startmenu'), 'Programs', 'Scoop Apps'))` `$([System.IO.Path]::Combine(`$env:SCOOP_STARTMENU`, 'Programs', 'Scoop Apps', 'Admin'))` *.lnk /XO /PURGE;"
}
```

It sets a few more environmental variables that install the program in the users directory instead of the admin's, so everything should take place in the user's profile. The only exception was the shortcut creation process, since it doesn't have an optional environmental variable (it calls `[System.IO.Path]::Combine([Environment]::GetFolderPath('startmenu'), 'Programs', 'Scoop Apps')`). My hacky solution to this was to mirror the admin shortcut folder with the user profile into a new folder in the start menu. I created an environmental variable for it, however, so someone could change scoop itself to accept an environmental variable for the shortcut folder if they wanted.

**Comment by scott-8** [comment]
@Ash258 before I close this, do you think it's possible to make the shortcut path configurable by changing the `shortcut_folder` function in `shortcuts.ps1` to something like this?

```powershell
function shortcut_folder($global) {
    $directory = $env:SCOOP_STARTMENU, (get_config 'shortcutPath'), [System.IO.Path]::Combine([Environment]::GetFolderPath('startmenu'), 'Programs', 'Scoop Apps') | Where-Object { -not [String]::IsNullOrEmpty($_) } | Select-Object -First 1
    if($global) {
        $directory = [System.IO.Path]::Combine([Environment]::GetFolderPath('commonstartmenu'), 'Programs', 'Scoop Apps')
    }
    return $(ensure $directory)
}
```

**Comment by Ash258** [comment]
#2547

**Comment by LoZeno** [comment]
@scott-8 A thought that came to me this morning: in case your administrator user profile has its own scoop instance running, you might want to prepend your scoop path to the admin's PATH, instead of appending it, to make sure that the right instance of scoop is run:
```
`$env:Path = \`"$env:USERPROFILE\scoop\shims;\`"+`$env:Path;
```
or something along the line of this.

**Comment by scott-8** [comment]
That's a good change, thanks!
