### ISSUE TITLE
idea-ultimate@2019.3: hash check failed

### ISSUE THREAD

**Issue by qiaoqiao888** [lukesampson/scoop-extras#3280]
App:         extras/idea-ultimate
URL:         https://download.jetbrains.com/idea/ideaIU-2019.3.win.zip
First bytes: 50 4B 03 04 0A 00 00 08
Expected:    ed31f98e363e3cca0c724f41e3781ab45987ebecbe572fca031cf833841aee1f
Actual:      4951353eea821af14ddab9386fb9faab33a7677d3a527b9e1c45196afac38f41

**Comment by Ash258** [comment]
Cannot reproduce [provided hash](https://download.jetbrains.com/idea/ideaIU-2019.3.win.zip.sha256) is correct.

Are you sure your scoop is up to date?
Please run `scoop update; scoop cache rm idea-ultimate; scoop uninstall idea-ultimate; scoop install idea-ultimate`

Hash mismatch could be caused by these factors:

- Network error
- Antivirus configuration
- Site is blocked (Great Firewall of China, Corporate restrictions, ...)

![image](https://user-images.githubusercontent.com/13260377/69854084-7cfc8e80-1288-11ea-971c-b4eead417710.png)

**Comment by qiaoqiao888** [comment]
I have used the latest download for the same thing. hash verification failed

![搜狗截图20191129163549](https://user-images.githubusercontent.com/18333714/69855385-5c532980-12c6-11ea-8423-283033b7e199.jpg)

**Comment by qiaoqiao888** [comment]
Uninstalled, re-downloaded, still the same situation

**Comment by Ash258** [comment]
What happen when you open downloaded file in 7zip/winrar/windows explorer?

**Comment by qiaoqiao888** [comment]
It is normal to use decompression software to open, scoop verification hash fails
![搜狗截图20191129164435](https://user-images.githubusercontent.com/18333714/69855963-8d802980-12c7-11ea-9dd2-73966095ae0b.jpg)
scoop cache directory file verification fails

**Comment by qiaoqiao888** [comment]
![image](https://user-images.githubusercontent.com/18333714/69858273-9d4e3c80-12cc-11ea-9ed0-c4d346dd3284.png)
Not expected
ed31f98e363e3cca0c724f41e3781ab45987ebecbe572fca031cf833841aee1f

**Comment by jesse996** [comment]
i got the same issue
Downloading new version
ideaIU-2019.3.win.zip (752.4 MB) [============================================================================] 100%
Checking hash of ideaIU-2019.3.win.zip ... ERROR Hash check failed!
App:         jetbrains/IntelliJ-IDEA-Ultimate
URL:         https://download.jetbrains.com/idea/ideaIU-2019.3.win.zip
First bytes: 50 4B 03 04 0A 00 00 08
Expected:    ed31f98e363e3cca0c724f41e3781ab45987ebecbe572fca031cf833841aee1f
Actual:      4951353eea821af14ddab9386fb9faab33a7677d3a527b9e1c45196afac38f41

Please try again or create a new issue by using the following link and paste your console output:
https://github.com/Ash258/Scoop-JetBrains/issues/new?title=IntelliJ-IDEA-Ultimate%402019.3-193.5233.102%3a+hash+check+failed

**Comment by qiaoqiao888** [comment]
Same thing happened with my other computers

**Comment by dragondove** [comment]
Same Problem, can I just skip hash check?

**Comment by Ash258** [comment]
I just fast checked again and I still cannot reproduce from 4 different world wide locations (Czech, Romania, GB, Canada) and internet providers.

You can surely skip the hash check with `-s` parameter to install command, but since you cannot be sure this file is valid and it was not infected by anything I would not suggest it.

First check the size of the file, content of downloaded archive. If it look correct, then you I would say you could skip the hash check

**Comment by dragondove** [comment]
I've already updated it by using `-s` parameter. For security, I use Windows Defender to scan virus and it seems no virus there. The program runs well, too. I'm in China, and the hash code is also 4951353eea821af14ddab9386fb9faab33a7677d3a527b9e1c45196afac38f41, which is the same with the issue provider.

**Comment by qiaoqiao888** [comment]
I tried to download it again, and the hash has been verified. I didn't do any modification. Good, has solved my problem

**Comment by dragondove** [comment]
I found that the zip file will directly downloaded to %userprofile%\apps\idea-ultimate\2019.3, not to the cache folder. Is this the reason cause this problem? (The file will be move to cache folder after I skip hash check and installation)

**Comment by dragondove** [comment]
This problem is not made by this bucket. I tried to download from jetbrains website. Got the same hash code. It might be a bug made by jetbrains.

**Comment by Ash258** [comment]
New version is available
