### ISSUE TITLE
pureref install not working anymore

### ISSUE THREAD

**Issue by Celeborn2BeAlive** [lukesampson/scoop-extras#3921]
Just tried to install [pureref](https://www.pureref.com/) with scoop but if failed:
```
The remote server returned an error: (404) Not Found.
URL https://www.pureref.com/files/portable.php?build=WIN64#/PureRef.exe is not valid
```
I checked quickly, it seems they changed their download scheme with some downloadKey in the URL, not sure if it is possible to automate it with scoop (never written a scool installer so I really don't know).

@MunsterPlop you did the integration according to history, maybe you want to take a look or remove the installer.

**Comment by MunsterPlop** [comment]
Thank you for notifying me.

I just saw their revamp.
Their download key might make it a bit trickier.
I'll look into it when I have some time.

**Comment by MunsterPlop** [comment]
I had a look and tried to do something with their new system but can't really figure it out.
I don't have a lot of time to work on it either so if someone more proficient with scoop can have a look,
it would be great.
Otherwise, I might as well remove the recipe.
I also looked into alternatives to pureref like Kuadro, I might take the time to make a recipe for it at some point.

**Comment by MunsterPlop** [comment]
The manifest has been removed a while back, so this issue should be closed.
