### ISSUE TITLE
sumatrapdf, installs 32 portable version

### ISSUE THREAD

**Issue by michael-angelozzi** [lukesampson/scoop-extras#4098]
sumatrapdf install 32 bit portable, even though I use 64 bit computer. Also the portable version is not to useful because it can't be set as the system default pdf viewer in Windows 10 ([see post like theres](https://superuser.com/questions/1376736/sumatrapdf-via-scoop-how-to-set-as-default-application)).

**Comment by vuwjzl17985** [comment]
Probably, it is not the 32bit issue. If you look at https://github.com/lukesampson/scoop-extras/blob/494aa32db8bb7697e1cc325201adfe0b92ea5843/bucket/sumatrapdf.json, scoop will automatically download sumatrapdf installer based on your architecture (32bit/64bit). So I guess you already installed the 64bit program. 

Of course, you can check whether you installed the correct version (32bit/64bit). Here is [the solution](https://www.ghacks.net/2016/12/09/find-out-if-a-windows-program-is-32-bit-or-64-bit/).

I also have this problem. But I guess it is caused by the default app setting. I have no idea on how to fix it.

**Comment by worldadventurer** [comment]
I just checked my scoop installed version of SumatraPDF. I launched it and in the center it shows the version and bit. For me (I'm running Windows 10 x64), it says: "v3.2 64-bit". See screenshot. 

@vuwjzl17985 is correct - Sumatra automatically installed the 64bit version for me.

![image](https://user-images.githubusercontent.com/4510725/83850698-df58af00-a743-11ea-997b-c03718bad4cd.png)
