### ISSUE TITLE
keypirinha trojan found

### ISSUE THREAD

**Issue by Ma3yTa** [lukesampson/scoop-extras#4179]
![image](https://user-images.githubusercontent.com/660379/83325794-5d770a80-a299-11ea-8220-b154f6e3905d.png)
![image](https://user-images.githubusercontent.com/660379/83325798-636ceb80-a299-11ea-8427-03f67ac72095.png)

**Comment by rikuben** [comment]
[Keypirinha Zip VirusTotal](https://www.virustotal.com/gui/file/8e8243bc40553e23dfe39164ef85b4a02663f0804ccb3f18d997b2da5f41b889/detection)
[Keypirinha Exe VirusTotal](https://www.virustotal.com/gui/file/2fd9eab8445fa643128466d981da83fe80a2492b569f06c613a8f4d294dfb2ea/detection)
Related Issues: Keypirinha/Keypirinha#453

Basically, false positive because of no code signing
