### ISSUE TITLE
Remove extras/apache64bit as it duplicates scoop/apache

### ISSUE THREAD

**Issue by rasa** [lukesampson/scoop-extras#461]
Let's delete https://github.com/lukesampson/scoop-extras/blob/master/apache64bit.json
as it duplicates https://github.com/lukesampson/scoop/blob/master/bucket/apache.json, OK?

**Comment by lukesampson** [comment]
Is this related to lukesampson/scoop#1552? If Apache 64 bit is experimental then it would be better to remove the 64-bit version from the manifest in the main bucket.

**Comment by rasa** [comment]
@lukesampson No, apachelounge.com doesn't say the 64-bit builds are experimental, or beta quality. It just seems to be a dup.

**Comment by lukesampson** [comment]
OK thanks for checking.

IIRC, the reason 64-bit Apache is here is so `scoop install apache php` gave you compatible 32-bit install or Apache while 64-bit PHP was still experimental. This is going back a year or three — I haven't been following developments since then. So if 64-bit Apache/PHP is all good now then please go ahead.
