### ISSUE TITLE
Travis cli

### ISSUE THREAD

**Issue by Alxandr** [lukesampson/scoop-extras#472]
Could you add support for travis CLI please? Requires ruby and is installed as such:

```
gem install travis -v 1.8.8 --no-rdoc --no-ri
```

**Comment by matthewjberger** [comment]
I think ideally you'd just do this by running:

`scoop install ruby`

and then running the command in your comment

**Comment by Alxandr** [comment]
@matthewjberger sure, that's what I do today. It'd just be nice if I didn't have to remember the command above, and could just `scoop install travis`, and it'd install ruby if I didn't already have it and then run the command.

**Comment by matthewjberger** [comment]
[It looks as if the `--no-rdoc --no-ri` syntax is deprecated now](https://stackoverflow.com/a/17201281). According to that stackoverflow link 

> The recommended way is to use --no-document in ~/.gemrc or /etc/gemrc.

that leaves you with just:
`gem install travis -v 1.8.8`

which gem will automatically install if 1.8.8 is the latest version:
`gem install travis` 

which is much simpler to remember, and if you need a specific version that can always just be appended.

In my opinion it makes more sense to use scoop to download programs that can't already be installed through some package manager already or to use scoop to download package managers for specific groups of programs, such as `npm` and `gem`. This also helps to avoid conflicts between packages that can be installed with different package managers, like how all of the node packages can be installed with either `yarn` or `npm`.

However, I definitely see where you're coming from with this idea though! I considered making a manifest for [Nyaovim](https://github.com/rhysd/NyaoVim) because I use that frequently, but I decided against it for the reasons stated above.
