### ISSUE TITLE
Merge issue on scoop update

### ISSUE THREAD

**Issue by adnaanbheda** [lukesampson/scoop-extras#4755]
![image](https://user-images.githubusercontent.com/25040547/93060011-2cc3b100-f68f-11ea-8828-5820d6482953.png)

I had to delete gcfscape.json to merge/update successfully, I hadn't made any changes to the json file.

Shouldn't it be doing a force merge ?

**Comment by Ma3yTa** [comment]
I had the same problem today:
![](https://i.imgur.com/BGXNC0L.png)

**Comment by FDUZS** [comment]
Same here.

```
Zheng :: ~ » scoop update
Updating Scoop...
Updating 'extras' bucket...
error: Your local changes to the following files would be overwritten by merge:
        bucket/tcno-acc-switcher.json
        bucket/vtfedit.json
Please commit your changes or stash them before you merge.
Aborting
Updating 'java' bucket...
Updating 'main' bucket...
Updating 'nerd-fonts' bucket...
Updating 'nirsoft' bucket...
Updating 'php' bucket...
Updating 'spoon' bucket...
Updating 'versions' bucket...
Scoop was updated successfully!
```

**Comment by r15ch13** [comment]
That's a whitespace problem caused by (https://github.com/lukesampson/scoop-extras/commit/ea6bb05d36b97be5a4e93dd05e8344262ff0adf8 / https://github.com/lukesampson/scoop-extras/commit/4a0db4b234b68a3abd76cff28bc9ef5c204d4ac5). The automated update fixed the whitespaces (https://github.com/lukesampson/scoop-extras/commit/998d1f13650b90a5abc848d698658fa648d3d28a / https://github.com/lukesampson/scoop-extras/commit/4a0db4b234b68a3abd76cff28bc9ef5c204d4ac5) but Git on windows doesn't care. :grin:

Simply remove and readd the bucket to fix this issue:
```
scoop bucket rm extras
scoop bucket add extras
```

**Comment by adnaanbheda** [comment]
@r15ch13 how is this preventable in the future ?

**Comment by r15ch13** [comment]
This should have been caught by the tests. But I don't know why it got through 😕
