### ISSUE TITLE
geekbench 5.3.1: Executable geekbench_gui.exe and geekbench.exe say wrong architecture

### ISSUE THREAD

**Issue by sinni800** [lukesampson/scoop-extras#5185]
![grafik](https://user-images.githubusercontent.com/2879097/100244337-195a7f00-2f37-11eb-837f-f3fb51e1a5ad.png)

![grafik](https://user-images.githubusercontent.com/2879097/100244472-3ee78880-2f37-11eb-8728-3641f7987fb8.png)

"The executable is valid, but meant for another type of computer"

`Die Version von C:\Users\sinni\scoop\apps\geekbench\current\geekbench_gui.exe ist mit der ausgeführten Windows-Version nicht kompatibel. Überprüfen Sie die Systeminformationen des Computers, und wenden Sie sich anschließend an den Herausgeber der Software.`

The version of geekbench_gui is not compatible with the running windows version. Check the system information of the computer and then ask the publisher of the software.

When I use sigcheck from sysinternals to analyze the file, I get:

```
Sigcheck v2.80 - File version and signature viewer
Copyright (C) 2004-2020 Mark Russinovich
Sysinternals - www.sysinternals.com

C:\Users\sinni\scoop\apps\geekbench\current\geekbench_gui.exe:
        Verified:       Signed
        Signing date:   19:17 14.11.2020
        Publisher:      Primate Labs Inc.
        Company:        n/a
        Description:    n/a
        Product:        n/a
        Prod version:   n/a
        File version:   n/a
        MachineType:    64-bit ARM
```

**Comment by davidxuang** [comment]
This seems caused by file duplication:

![image](https://user-images.githubusercontent.com/24728204/100379235-75430780-300c-11eb-9396-039555f233f9.png)

The larger one is for x64 and the smaller one is for arm64 (so by the way, `architecture/64bit` is missing), and the arm64 binary will override x64 one while being extracted as archive.

As far as I know `uniextract2` will extract both files: 

![image](https://user-images.githubusercontent.com/24728204/100379725-46796100-300d-11eb-948c-f621bfa3ca00.png)

Also Nullsoft is giving a [guide](https://nsis.sourceforge.io/Can_I_decompile_an_existing_installer). I'm not so familiar with this format so I can't really find an easy way to solve this.
