### ISSUE TITLE
Is this thing dead?

### ISSUE THREAD

**Issue by cprieto** [lukesampson/scoop-extras#6113]
Honest question, is this thing dead? do you need help?

I am seeing PRs and automatic PRs coming from failed hash checks piling and not being merged (some PRs with verification fixes has been there for weeks and not rejected, fixed or merged).

But at the same time I can see new additions every day in the repository, some of us want to help if there is a problem with too many requests and stuff so if you need some help just ask to the community.

**Comment by Ash258** [comment]
No. Extras is covered.

New manifests are merged on Sunday/Monday after proper review, which takes time.

Hash fixes are not merged until they are properly tested and checked that files are not compromised. And since most of the authors do not provide any information about them in most time they will not be merged by me. Also I am not going to support incompetent vendors which cannot keep stable release artifacts and have to change them 10 times without any information about what was changed and why.

**Comment by cprieto** [comment]
Really?

DosBox-x has been "verified" for weeks now, what is the problem there?
