### ISSUE TITLE
301 Moved Permanently

### ISSUE THREAD

**Issue by barchard** [lukesampson/scoop-extras#668]
https://github.com/lukesampson/scoop-extras/blob/5364f3e9ce9bc5019814971629dd71f6ecc50ffe/eclipse-platform.json#L7

<img width="942" alt="screen shot 2017-11-28 at 11 09 40 am" src="https://user-images.githubusercontent.com/17622/33330370-aea04d9c-d42c-11e7-97ca-74de421844d9.png">

**Comment by r15ch13** [comment]
This happens because `https://version-to-train.azurewebsites.net/` redirects from `HTTPS` to `HTTP` (`http://archive.eclipse.org`). This is a security feature and therefore it throws an error.

@se35710 is it possible to use `https://www.eclipse.org/downloads/download.php` with `HTTPS` instead?

Related to: https://github.com/se35710/train-to-version

**Comment by se35710** [comment]
It’s in PR #575.

**Comment by se35710** [comment]
@r15ch13 I can remake it based on latest pull so we don’t have to merge if you’d like?

**Comment by r15ch13** [comment]
@se35710 yeah that would be better. I fucked up your PR 😀
