### ISSUE TITLE
Rust and cargo manifests need updating

### ISSUE THREAD

**Issue by anurse** [lukesampson/scoop-extras#97]
There are some issues with the `rust-nightly` and `cargo-nightly` manifests. Because they generate shim exes, the `cargo` build tool has trouble shelling out to the `rustc` compiler (see https://github.com/rust-lang/cargo/issues/1661). Also, cargo is no longer a separate component, it is generally packaged together with rust so having a separate manifest for it is confusing.

I'll be submitting a PR for this momentarily. It's fixed the issue in my environment, but I'll loop in the original submitters of the `{rust,cargo}-nightly` manifest so they can take a look too.

Scoop-Extras should (and my PR will):

1. Remove the `cargo-nightly` manifest, since `rustc` and `cargo` are generally installed together from a single MSI
2. Change from using shims to `env_add_path` because otherwise rust-lang/cargo#1661 gets in the way. I'd still like to track down why the shim isn't working, since I prefer the shim mechanism, but for now this will fix the issue.

**Comment by lukesampson** [comment]
Thanks for investigating this Andrew. I wonder if the shim could be fixed by switching [shim.cs](https://github.com/lukesampson/scoop/blob/master/supporting/shimexe/shim.cs) to use [Environment.CommandLine](https://msdn.microsoft.com/en-us/library/system.environment.commandline) instead of the parsed arguments.

**Comment by lukesampson** [comment]
Opened a new issue for this: lukesampson/scoop#382
